# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hazelcast-client}
  s.version = "0.0.1"
  s.platform = %q{jruby}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adrian Madrid"]
  s.date = %q{2011-01-07}
  s.default_executable = %q{hazelcast-client-console}
  s.description = %q{Hazelcast::Client is a little gem that wraps the Java Hazelcast Client library into a more comfortable JRuby package.}
  s.email = ["aemadrid@gmail.com"]
  s.executables = ["hazelcast-client-console"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/hazelcast-client-console",
    "lib/hazelcast-client.rb",
    "lib/hazelcast-client/map.rb",
    "lib/hazelcast-client/queue.rb",
    "lib/hazelcast-client/topic.rb",
    "test/helper.rb",
    "test/test_map.rb",
    "test/test_queue.rb",
    "test/test_topic.rb"
  ]
  s.homepage = %q{}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{hazelcast-client}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Connecting to a Hazelcast Cluster has never been easier!}
  s.test_files = [
    "test/test_map.rb",
    "test/test_queue.rb",
    "test/test_topic.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hazelcast-jars>, ["= 1.9.1"])
    else
      s.add_dependency(%q<hazelcast-jars>, ["= 1.9.1"])
    end
  else
    s.add_dependency(%q<hazelcast-jars>, ["= 1.9.1"])
  end
end

